# PostgreSQL (production)
# spring.datasource.url=jdbc:postgresql://localhost:5432/utilitymap
# spring.datasource.username=utilitymap
# spring.datasource.password=utilitymap
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# H2 (dev rapide)
spring.datasource.url=jdbc:h2:mem:utilitymap;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# CORS - Angular dev server
cors.allowed-origins=http://localhost:4200
